### ISSUE TITLE
Poppler required for `paginate`

### ISSUE THREAD

**Issue by DunklesArchipel** [conda-forge/svgdigitizer-feedstock#12]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

`poppler>=22,<23` is not included in the package list, but is required to use `svgdigitizer paginate PDF`

### Installed packages

```shell
poppler not included
```

### Environment info

```shell
echemdb/website environment
```

**Comment by saraedum** [comment]
An actual error message would have been very helpful. (I don't have a system without poppler around ;) )

**Comment by DunklesArchipel** [comment]
I think this is outdated and solved
